# Generated by Django 5.2.17 on 2026-08-29 05:24

import inventario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_custodio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodio',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[inventario.models.validar_cedula_ecuatoriana]),
        ),
    ]
