# Generated by Django 5.2.17 on 2026-08-29 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constatacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_constatacion', models.DateField()),
                ('estado_encontrado', models.CharField(choices=[('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=10)),
                ('encontrado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='constataciones', to='inventario.bien')),
            ],
        ),
    ]
