# Generated by Django 5.2.17 on 2026-09-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_bien_alto_bien_ancho_bien_caracteristicas_bien_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='condicion_original',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='custodio_original',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='dimensiones_originales',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='ubicacion_original',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bien',
            name='valor_compra_original',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
