# Generated by Django 5.2.17 on 2026-09-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_bien_condicion_original_bien_custodio_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('COMPRADO', 'Comprado'), ('DONADO', 'Donado')], max_length=20, null=True),
        ),
    ]
