# Generated by Django 5.2.17 on 2026-09-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_bien_procedencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='datos_adicionales_originales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
