# Generated by Django 5.2.17 on 2026-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_bien_datos_adicionales_originales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
