# Generated by Django 5.2.17 on 2026-09-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_alter_bien_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='numero_acta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
