# Generated by Django 5.2.17 on 2026-09-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_asignacion_numero_acta'),
    ]

    operations = [
        migrations.AddField(
            model_name='custodio',
            name='carrera',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='custodio',
            name='ciclo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='custodio',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='numero_acta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de acta'),
        ),
    ]
