# Generated by Django 5.2.17 on 2026-09-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_custodio_carrera_custodio_ciclo_custodio_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
