# Generated by Django 5.2.17 on 2026-09-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_alter_asignacion_fecha_asignacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='bienes',
            field=models.ManyToManyField(blank=True, related_name='asignaciones_multiples', to='inventario.bien'),
        ),
    ]
