# Generated by Django 5.2.17 on 2026-09-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_asignacion_bienes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='inventario.bien'),
        ),
    ]
