# Generated by Django 5.2.17 on 2026-09-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_alter_asignacion_bien'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='fecha_prevista_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha prevista de devolución'),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de devolución real'),
        ),
    ]
