# Generated by Django 5.2.17 on 2026-09-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_asignacion_fecha_prevista_devolucion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='bien',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='bienes/'),
        ),
    ]
